/*
 * This source file was generated by the Gradle 'init' task
 */
package com.demo.chessboard;

import com.demo.chessboard.entity.base.Position;
import com.demo.chessboard.enums.Side;
import com.demo.chessboard.factory.AbstractPieceFactory;
import com.demo.chessboard.factory.PieceFactory;
import com.demo.chessboard.service.ChessBoard;
import com.demo.chessboard.service.PieceMovementService;
import com.demo.chessboard.service.impl.MovementServiceImpl;

import java.util.Scanner;
import java.util.Set;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter the pieces (e.g., 'W: KE2, QD1, RA1, ...'): ");
        String input = scanner.nextLine();

        ChessBoard board = new ChessBoard();
        AbstractPieceFactory whiteFactory = new PieceFactory(Side.WHITE);
        AbstractPieceFactory blackFactory = new PieceFactory(Side.BLACK);

        PieceMovementService.parseInput(input, board, whiteFactory, blackFactory);
        MovementServiceImpl movementService = new MovementServiceImpl();

        System.out.println("\n==========RESULT==========");
        board.getAllPieces().forEach(piece -> {
            Set<Position> moves = movementService.calculateAvailableMoves(board, piece);
            System.out.printf("%s %s at %s can move: %s%n", piece.getSide(), piece.getType(), piece.getPosition(), moves);
        });

    }
}
