/*
 * This source file was generated by the Gradle 'init' task
 */
package com.demo.chessboard;

import com.demo.chessboard.entity.base.Piece;
import com.demo.chessboard.entity.base.Position;
import com.demo.chessboard.service.PieceMovementService;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;

public class Library {
    public static void main(String[] args) {
        PieceMovementService service = PieceMovementService.createPieceMovementService();
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter the pieces (e.g., 'W: KE2, QD1, RA1, ...'): ");
        String input = scanner.nextLine();

        Map<Piece, Set<Position>> resultSet = service.initializeAndCalculateMoves(input);

        System.out.println("\n==========RESULT==========");
        resultSet.forEach((piece, moves) -> System.out.printf("%s %s at %s can move: %s%n", piece.getSide(), piece.getType(), piece.getPosition(), moves));
    }
}
